### ISSUE TITLE
'Contao\NewsGalleryMigration' not found

### ISSUE THREAD

**Issue by phreak** [NothingInteractive/contao-news_migration#1]
Hi pfiaux, ich bin bei einem Update mit deinem Script hier in folgenden Fehler gelaufen. Kannst du damit etwas anfangen? Danke dir.

Fatal error: Class 'Contao\NewsGalleryMigration' not found in /www/htdocs/w0113806/system/modules/news_migration/config/runonce.php on line 22

![screen](https://cloud.githubusercontent.com/assets/368430/5691344/ec9ce690-98c1-11e4-8238-ac450c861849.png)

![screen2](https://cloud.githubusercontent.com/assets/368430/5691353/926e8254-98c2-11e4-8c14-45c4d824d520.png)

**Comment by christophengelmayer** [comment]
Bennene den Ordner 
`system/modules/news_migration`
um in 
`system/modules/newsgalleryC3Import`

Hat bei mir funktioniert.

**Comment by pfiaux** [comment]
Hello, like @slashadmin mentioned it looks like there's a path issue from the error outputs above.

I'm not familiar with the Live Update module as we have never used it, if it works similar to manually updating from a Contao 2.x to a 3.x version the problem might be that it runs in safe mode so the NewsGalleryMigration class might not be loaded. If that is the case I would suggest
- running the update without the migration module
  - (making sure not to delete any data tables or fields)
- turning off safe mode
- adding the news migration script
- going to the install or the update page to force the run once script to run

Then it should be able to run it and load the classes.

**Comment by pfiaux** [comment]
Since there's been no reply I assume it was a path problem and it is now solved.

**Comment by hanski** [comment]
The wrong path comes from config/autoload.php
